### ISSUE TITLE
New zsh sessions err due to completion

### ISSUE THREAD

**Issue by ggamel** [ggamel/dotfiles#3]
Currently dealing with the following:

```
Last login: Tue Jan 29 14:09:47 on ttys002
(anon):6: command not found: ___main
_default:compcall:12: can only be called from completion function
~  ⚡ 
```

Suspecting the issue is the latest git (1.8.1.2) plus hub (1.10.4). Had zero issues with this before I upgraded to git 1.8.1.2.

**Comment by j-walker23** [comment]
@larrylv you are they man!

**Comment by larrylv** [comment]
@j-walker23 glad to help.

**Comment by simenbrekken** [comment]
Got this after upgrading to :mount_fuji:, as per @larrylv removing `_git` works.

**Comment by ggamel** [comment]
Thanks @larrylv et al! :sunglasses: :+1:
